---
title: "RideShare in Austin"
author: "Francisco Marquez"
date: "11/4/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(jsonlite)
library(nnet)
library(twitteR)
library(stringr)
library(lubridate)
library(tidyverse)
library(ggthemes)
```

## R Markdown



```{r data_load}
df<-read_csv('atx_dwi_pi.csv')
#df%>%glimpse()
```

## What does data look like



```{r pressure, echo=FALSE}
df%>%
  rename(crime_type=`Highest Offense Description`,
         occ_datetime=`Occurred Date Time`)%>%
  mutate(datetime=mdy_hms(occ_datetime))%>%
  mutate(date=date(datetime))%>%
  filter(crime_type%in%c('DWI','PUBLIC INTOXICATION'))%>%
  filter(date>'2014-10-01')%>%
  mutate(fdate=floor_date(date,unit='month'))%>%
  mutate(rs = case_when(date>='2017-05-29'~1,
                       date<='2016-05-01'~1,
                       TRUE ~ 0))%>%
  group_by(crime_type,date,crime_type,rs)%>%summarise(events=n())%>%select(date,events,crime_type,rs)%>%
  ggplot(aes(x=date,y=events,color=as.factor(rs)))+geom_point()
```

Okay, data looks messy. I'm going to group by month

```{r grouped}
mly_dat<-df%>%
  rename(crime_type=`Highest Offense Description`,
         occ_datetime=`Occurred Date Time`)%>%
  mutate(datetime=mdy_hms(occ_datetime))%>%
  mutate(date=date(datetime))%>%
  filter(date>'2014-10-01')%>%
  filter(crime_type%in%c('DWI','PUBLIC INTOXICATION'))%>%
  mutate(fdate=floor_date(date,unit='month'))%>%
  mutate(rs = case_when(date>='2017-05-29'~0,
                        date<='2016-05-01'~0,
                        TRUE ~ 1))%>%
  mutate(rs=as.factor(rs))%>%
  group_by(crime_type,fdate,rs)%>%summarise(events=n())%>%select(fdate,crime_type,rs,events)%>%ungroup()%>%
  mutate(tl = 1:n())

mly_dat%>%
  ggplot(aes(x=fdate,y=events,color=rs))+geom_point()+facet_wrap(~crime_type)+
  labs(x='Date',y='Arrests',title='Austin Arrest Cases',color='RideShare Unavailable',subtitle = '')+
  theme_few()

mly_dat%>%
  ggplot(aes(x=fdate,y=events,color=crime_type))+geom_point()+
  theme_few()+
  #scale_colour_brewer(palette = "Dark2")+
  labs(x='Date',y='Arrests',title='Austin Arrest Cases',color='Crime',subtitle = '')+
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = 'white'),
        plot.title=element_text(family="sans", face="bold",size=22),
        axis.text=element_text(size=15),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        strip.text.x = element_text(size = 16, colour = "orange"),
        plot.caption=element_text(family="sans", face="bold",size=20))+scale_fill_hc()
  
```

```{r dd_regression}
data<-mly_dat%>%filter(fdate<='2017-06-01')%>%
  mutate(crime_type = factor(crime_type,levels = c("PUBLIC INTOXICATION","DWI")))%>%
  mutate(D = ifelse(crime_type=='DWI',1,0))

dd<-lm(formula=events ~ D + rs + rs*D, data=data)
summary(dd)
```



It doesn't look like RideShare had an effect on DWI charges. Good job Austin!